name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Restore mvn cache
        id: maven-cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ hashFiles('flow-core/pom.xml') }}
          restore-keys: |
            ${{ hashFiles('flow-core/pom.xml') }}

      - name: Download dependencies
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: >
          cd flow-core &&
          mvn clean install
          -DskipTests=true

      #  Tests run automatically
      - name: Build
        env:
          SECRET: ${{ secrets.SECRET }}
          STAGE: test
        run: >
          cd ./flow-core && 
          mvn clean package
