name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Restore mvn cache
        id: maven-cache
        uses: actions/cache@v2
        with:
          path: ~/mvn/caches
          key: ${{ hashFiles('userSource/pom.xml') }}
          restore-keys: |
            ${{ hashFiles('userSource/pom.xml') }}

      - name: Download dependencies
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: >
          cd userSource &&
          mvn clean install
          -DskipTests=true

      - name: Integration Tests
        run: cd ./userSource && mvn clean test
